### ISSUE TITLE
Polya Link not working

### ISSUE THREAD

**Issue by oliverwiehr** [franklinvp/foobar#1]
Howdy, I'm doing the foobar challenges and reading up on the Polya Enumeration Theorem. I noticed that this link isn't working: https://franklinvp.github.io/2020-06-05-PolyaFooBar/. Would love to take a look at that page :)

**Comment by franklinvp** [comment]
Yes, I need to find some time to put up that website. Note that it is a GitHub pages site. So, there is a repository from where it is generated. [This](https://github.com/franklinvp/franklinvp.github.io/blob/master/_posts/2020-06-05-PolyaFooBar.md) would be the corresponding Markdown file.
